cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'tmux'
brew 'awscli'
brew 'htop'
brew 'fnm'
brew 'git'
brew 'openssl'
brew 'unar'
brew 'gpg'
brew 'zsh-syntax-highlighting'
brew 'zsh-autosuggestions'
brew 'stern'
brew 'terraform'
brew 'gh'
brew 'helm'
brew 'gpg'
brew 'pinentry-mac'
brew 'jq'
brew 'watch'
brew 'cloudflared'

cask 'visual-studio-code'
cask 'google-cloud-sdk'
cask 'discord'
brew 'kubectl'
brew 'ansible'
cask 'omnidisksweeper'
cask 'telegram'
cask 'keybase'
cask 'postman'
cask 'vlc'
cask 'spectacle'
cask 'figma'
cask 'tradingview'
cask 'nordvpn'
cask 'transmission'
cask 'tunnelblick'
cask 'notion'
cask 'vnc-viewer'
#cask 'alfred'
# cask 'transmit'
