#!/usr/bin/env bash

isWorkMachine=false

# Start
echo "$(basename "$0") starting."

read -r -p "Is this a work machine? (y/n) " -n 1
echo
if [[ $REPLY =~ ^[Yy]$ ]] ; then
    isWorkMachine=true
fi

# homebrew options
export HOMEBREW_CASK_OPTS="--require-sha"

# Ask for the administrator password upfront
sudo -v

# setup taps

# install applications
brew cask install docker
brew cask install iterm2
brew cask install sublime-text
brew cask install vagrant
brew cask install visual-studio-code

#Note: Required privileges access
#brew cask install virtualbox
#brew cask install virtualbox-extension-pack

brew cask install alfred
brew cask install 1password
brew cask install little-snitch
brew cask install cyberduck
brew cask install cleanmymac
brew cask install google-chrome
brew cask install tunnelbear
brew cask install postman

# applications that are not immediately needed
brew cask install dropbox
brew cask install skype
brew cask install vlc
brew cask install spectacle
brew cask install tower
brew cask install keybase
brew cask install calibre
brew cask install telegram
brew cask install macdown
brew cask install slack
brew cask install omnidisksweeper
brew cask install etcher

# if this is a work machine
if [[ $isWorkMachine == true ]] ; then
 brew cask install zoomus
fi

# cleanup unneeded files
brew cleanup

# Finished
echo "$(basename "$0") complete."
